### ISSUE TITLE
Expose a fetcher

### ISSUE THREAD

**Issue by zachequi** [Modern-Treasury/modern-treasury-node#141]
It would be very handy to pass a fetcher directly into the ModernTreasury SDK client for consumers who use alternative fetchers, or custom fetchers that e.g. have logging side effects.

**Comment by rattrayalex** [comment]
Oh hi Zach! Good to see you here 😄 (I help maintain MT's SDKs).

We definitely want to add support for middleware to inspect, edit, and log each request/response, but haven't gotten around to it yet. We're _slightly_ reticent to expose custom fetchers just yet, simply so that we can elicit more use-cases for higher-level helpers. 

Now might be a fairly good time to add this; can you share more about what you're looking to do, either here or over [email](mailto:alex@stainlessapi.com)? Would love your feedback.

**Comment by rattrayalex** [comment]
Fixed in https://github.com/Modern-Treasury/modern-treasury-node/pull/144

**Comment by rattrayalex** [comment]
This has been released in 2.1.0
